[package]
name = "clipboard-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[features]
bindgen-cli = ["uniffi/cli"]

[[bin]]
name = "clipboard-uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["bindgen-cli"]

[dependencies]
clipboard-core = { path = "../clipboard-core" }
clipboard-store = { path = "../clipboard-store" }
uniffi.workspace = true
