/// Markers that declare the pasteboard contents as secret (password managers, secure fields).
///
/// Entries are written in lowercase because matching is ASCII case-insensitive; producers of
/// these markers are not consistent about capitalization.
const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.concealedtype",
    "com.agilebits.onepassword",
];

/// Markers that declare the pasteboard contents as not worth persisting.
///
/// `org.nspasteboard.AutoGeneratedType` stays here rather than in `CONCEALED_TYPES` because
/// nspasteboard.org defines it as "generated by an application, the user had no intention to
/// Copy" and not as confidential; it is excluded from history but needs no display obfuscation.
///
/// See the `CONCEALED_TYPES` note about lowercase entries and case-insensitive matching.
const TRANSIENT_TYPES: &[&str] = &[
    "org.nspasteboard.transienttype",
    "org.nspasteboard.autogeneratedtype",
    "de.petermaurer.transientpasteboardtype",
    "com.typeit4me.clipping",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FilterReason {
    Concealed,
    Transient,
}

#[derive(Clone, Copy, Debug, Default)]
pub struct CaptureFilter;

impl CaptureFilter {
    /// Evaluates the pasteboard's advertised types before any payload bytes are read.
    ///
    /// Every advertised type is checked, so a single marker anywhere in the list rejects the
    /// whole pasteboard (fail-safe OR). Comparison ignores ASCII case; concealed markers are
    /// reported before transient ones when both appear.
    pub fn evaluate_types(&self, pasteboard_types: &[String]) -> Result<(), FilterReason> {
        let mut transient = false;
        for pasteboard_type in pasteboard_types {
            if matches_marker(CONCEALED_TYPES, pasteboard_type) {
                return Err(FilterReason::Concealed);
            }
            if matches_marker(TRANSIENT_TYPES, pasteboard_type) {
                transient = true;
            }
        }
        if transient {
            return Err(FilterReason::Transient);
        }
        Ok(())
    }

    /// The concealed markers this filter rejects, lowercase. Exposed so callers outside the
    /// crate can exercise the policy without maintaining a second copy of the list.
    pub fn concealed_markers(&self) -> &'static [&'static str] {
        CONCEALED_TYPES
    }

    /// The transient markers this filter rejects, lowercase. See `concealed_markers`.
    pub fn transient_markers(&self) -> &'static [&'static str] {
        TRANSIENT_TYPES
    }
}

fn matches_marker(markers: &[&str], pasteboard_type: &str) -> bool {
    markers
        .iter()
        .any(|marker| marker.eq_ignore_ascii_case(pasteboard_type))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn types(values: &[&str]) -> Vec<String> {
        values.iter().map(|value| (*value).to_owned()).collect()
    }

    #[test]
    fn concealed_marker_is_rejected_without_becoming_a_representation() {
        let advertised_types = types(&["org.nspasteboard.ConcealedType", "public.utf8-plain-text"]);
        assert_eq!(
            CaptureFilter.evaluate_types(&advertised_types),
            Err(FilterReason::Concealed)
        );
    }

    #[test]
    fn ordinary_storage_types_are_accepted() {
        let advertised_types = types(&["public.utf8-plain-text", "public.html"]);
        assert_eq!(CaptureFilter.evaluate_types(&advertised_types), Ok(()));
    }

    #[test]
    fn every_concealed_marker_is_rejected() {
        for marker in CONCEALED_TYPES {
            assert_eq!(
                CaptureFilter.evaluate_types(&types(&[marker])),
                Err(FilterReason::Concealed),
                "{marker} was not treated as concealed"
            );
        }
    }

    #[test]
    fn every_transient_marker_is_rejected() {
        for marker in TRANSIENT_TYPES {
            assert_eq!(
                CaptureFilter.evaluate_types(&types(&[marker])),
                Err(FilterReason::Transient),
                "{marker} was not treated as transient"
            );
        }
    }

    #[test]
    fn marker_matching_ignores_ascii_case() {
        assert_eq!(
            CaptureFilter.evaluate_types(&types(&["ORG.NSPASTEBOARD.CONCEALEDTYPE"])),
            Err(FilterReason::Concealed)
        );
        assert_eq!(
            CaptureFilter.evaluate_types(&types(&["De.PeterMaurer.TransientPasteboardType"])),
            Err(FilterReason::Transient)
        );
    }

    #[test]
    fn a_marker_anywhere_in_a_mixed_type_list_rejects_capture() {
        let advertised_types = types(&[
            "public.utf8-plain-text",
            "public.html",
            "public.rtf",
            "org.nspasteboard.AutoGeneratedType",
        ]);
        assert_eq!(
            CaptureFilter.evaluate_types(&advertised_types),
            Err(FilterReason::Transient)
        );
    }

    #[test]
    fn concealed_wins_over_transient_in_a_mixed_type_list() {
        let advertised_types = types(&[
            "org.nspasteboard.TransientType",
            "public.utf8-plain-text",
            "com.agilebits.onepassword",
        ]);
        assert_eq!(
            CaptureFilter.evaluate_types(&advertised_types),
            Err(FilterReason::Concealed)
        );
    }

    #[test]
    fn an_empty_type_list_is_accepted() {
        assert_eq!(CaptureFilter.evaluate_types(&[]), Ok(()));
    }
}
